### ISSUE TITLE
Looks interesting but seems to depend on the browser environment

### ISSUE THREAD

**Issue by mschipperheyn** [appuri/robust-websocket#1]
This library looks interesting. I work in React-Native, so the traditional browser objects are not always available. Am I correct in assuming that you depend on browser objects? One interesting way to avoid this, is to work with default methods that can be replaced through an options object. For instance, global event listeners for connect work differently in React-Native, but could easily be supplyied as a function reference.

**Comment by nathanboktae** [comment]
I'm not sure of the environment React Native is running in but I have tests for WebWorkers and `document` and `window` are not available there, so no I don't depend those browser objects. I depend on [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) which if missing, the polyfill for it requires `document` so if `CustomEvent` is available, I'm quite sure it'll work.

**Comment by nathanboktae** [comment]
Any updates @mschipperheyn ? did you have success with React-Native?

**Comment by mschipperheyn** [comment]
Hi. I didn't have time to test it yet

**Comment by sachinrekhi** [comment]
FYI, I just tested using robust-websocket in React Native 0.39.2 and it worked successfully without issue. This is great because unfortunately reconnectingwebsocket does not work with React Native because of it's dependence on the document object for generating events.

**Comment by nathanboktae** [comment]
Great to hear thanks @sachinrekhi ! I'll close this, but suggestions or a PR on how to test React Native would be welcome.

**Comment by sachinrekhi** [comment]
Actually I spoke to soon. Looks like it works fine in the iOS Simulator, but once I pushed to production I got "Can't find variable: CustomEvent". And as you mentioned, the polyfill requires document, which is not available in the React Native javascript environment.

**Comment by nathanboktae** [comment]
That's odd... Support for CustomEvent in iOS [goes back to iOS 6 according to caniuse.com](http://caniuse.com/#search=CustomEvent) how old of devices do you have to support?
