### ISSUE TITLE
Event.currentTarget is readOnly

### ISSUE THREAD

**Issue by halt-hammerzeit** [appuri/robust-websocket#10]
https://developer.mozilla.org/ru/docs/Web/API/CustomEvent
https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-Event-currentTarget

```js
RobustWebSocket.prototype.dispatchEvent = function (event) {
  if (!(event.type in this.listeners)) {
    return;
  }
  event.currentTarget = this;
```

A contradiction?

**Comment by nathanboktae** [comment]
Thanks. I have even been asserting that `currentTarget` is actually [the `WebSocket` instance this whole time](https://github.com/appuri/robust-websocket/blob/5318071033b006177c57eaf0fa14c5604e60ca33/test/tests.js#L185) because of that, lol.
