### ISSUE TITLE
Reconnect function doesn't work when connect fails with error code 500/503

### ISSUE THREAD

**Issue by hyee** [appuri/robust-websocket#16]
Function `newWebSocket` can trigger errors on line `realWs = new WebSocket(url, protocols)` , I did fix the code by referring to https://stackoverflow.com/questions/32462133/catch-websocket-exception-error-during-websocket-handshake-unexpected-respons , but don't think it so graceful.

Sample error message:
`connection to 'ws://<address>' failed: Error during WebSocket handshake: Unexpected response code: 500`

**Comment by sergio91pt** [comment]
Are you sure? In what browser?
According to the [specification](https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket), the connection is not done in the constructor, but in parallel after returning the object.
