### ISSUE TITLE
0.2.0 no longer works for me

### ISSUE THREAD

**Issue by dubiousdavid** [appuri/robust-websocket#3]
`0.1.0` works great, but `0.2.0` is not reconnecting for me. Here is my logic (uses Kefir FRP):

```javascript
import WebSocket from 'robust-websocket'
let ws = new WebSocket('wss://echo.websocket.org')

let online$ = Kefir.fromPoll(500, () => navigator.onLine).skipDuplicates()

let socketConnected$ = Kefir.stream(emitter => {
  ws.onopen = () => emitter.emit(true)
  ws.onclose = () => emitter.emit(false)
})

let connected$ = socketConnected$
  .combine(online$, (connected, online) => connected && online)
  .toProperty(() => false)
```

**Comment by nathanboktae** [comment]
Don't you mean `new RobustWebSocket`?  Also if you use `wss` are you also connecting from a page on |hyyps`?

**Comment by dubiousdavid** [comment]
Sorry, I updated the code sample. I'm doing an ES6 import earlier in the code.

**Comment by dubiousdavid** [comment]
Yes, it's connecting from an `https` page: https://dubiousdavid.github.io/muv.js/examples/websocket/

**Comment by nathanboktae** [comment]
That example uses ReconnectingWebSocket not RobustWebSocket. See line 4472.

A vanilla JS example (not babel, not your latest framework of the week) would help.

**Comment by nathanboktae** [comment]
Here's [my working codepen of 0.2.0](https://saucelabs.com/jobs/6fd141e7261843818127140156a3db25). Reopen if you have more insights.
