### ISSUE TITLE
Chrome v42 

### ISSUE THREAD

**Issue by swilsonnc** [appuri/robust-websocket#4]
Doesn't work on tablet with chrome v42 on it.  Normal websockets work fine.  Other devices with newer chrome work fine.  This tablet can't run a higher version.

**Comment by nathanboktae** [comment]
I just ran the tests on SauceLabs on Chrome 42 and [they passed](https://saucelabs.com/jobs/6fd141e7261843818127140156a3db25). What errors are you seeing? You may need to provide the polyfills [as stated in the readme](https://github.com/appuri/robust-websocket#polyfills-needed)

**Comment by swilsonnc** [comment]
I found a way to update the tablet to Android 5.1.1 and am able to use a higher version of chrome now.  I am pretty sure it was Robust-websocket causing the problem in v42 though.  I could use "var was = new Websocket(etc etc)" and it work fine.  Change Websocket to RobustWebsocket and the page loads but the Websocket values won't load in.

**Comment by nathanboktae** [comment]
Here's the tests passing [on Android 4.4](https://saucelabs.com/jobs/dd4a9563b4fb49e487a7579958a5241d). Likely you were missing [the polyfills needed](https://github.com/appuri/robust-websocket#polyfills-needed).

**Comment by swilsonnc** [comment]
You closed it but what you're not understanding is it's a chrome v42
issue.  Not a Android 4 issue.  The normal browser and Firefox worked fine,
chrome didn't.  Did you check using chrome v42 on Android v4.4 on
saucelabs?  If so then I am sorry for the misunderstanding.

Thanks,
Scott

**Comment by nathanboktae** [comment]
> what you're not understanding is it's a chrome v42 issue.

In my very first reply I linked the SauceLabs tests [proving it works](https://saucelabs.com/jobs/6fd141e7261843818127140156a3db25). You have given me no evidence or hint as to what your problem is, nor did you answer my other question - Did you add the necessary polyfills?

> Did you check using chrome v42 on Android v4.4 on saucelabs?

The built-in browser on android works - [again here's the passing tests](https://saucelabs.com/jobs/dd4a9563b4fb49e487a7579958a5241d).

**Comment by swilsonnc** [comment]
Yes the built in browser works fine.  If you download Chrome from the play
store, which is v42, it does not work correctly.

Thanks,
Scott Wilson
Network Administrator
Country Cablevision, Inc.
9449 State Highway 197 S
Burnsville, NC  28714
O: 828-682-4074
C: 828-284-2939
