### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by john-doherty** [appuri/robust-websocket#6]
Please can you add an example of setting up a RobustWebSocket and how to assign shouldReconnect function etc?

**Comment by nathanboktae** [comment]
The readme has a link to a [CodePen example](https://codepen.io/nathanboktae/pen/RoLXmw) and [3 examples](https://github.com/appuri/robust-websocket#shouldreconnect) of `shouldReconnect` functions. Can you be more specific on what is lacking here?

**Comment by john-doherty** [comment]
To increase adoption it needs to be obvious, so a few examples of the constructor with all options listed. I was not sure how to create a new socket and get it to use the shouldReconnect method, I had to sift through the code. 

Something like this (but with all options):

```
var ws = new RobustWebSocket('ws://127.0.0.1:8080', null, {
    timeout: 5000, 
    shouldReconnect: function(){
        return ws.reconnects <= 20 && 0
    }
});
```

or

```
var ws = new RobustWebSocket('ws://127.0.0.1:8080', function(){
    return ws.reconnects <= 20 && 0;
});
```

I tend to heavily comment [my stuff](https://github.com/john-doherty/node-iframe-replacement#example-server)

**Comment by nathanboktae** [comment]
I see what you mean. the info is there but it's a different style, but I like that style too.

How about something like this for a new Usage section?

## Usage

[CodePen Example](https://codepen.io/nathanboktae/pen/RoLXmw)

Use it as you would a normal websocket:

```javascript
var ws = new RobustWebSocket('ws://echo.websocket.org/')

ws.addEventListener('open', function(event) {
  ws.send('Hello!')
})

ws.addEventListener('message', function(event) {
  console.log('we got: ' + event.data)
})
```

But with an optional set of options you can specify as a 3rd parameter

```javascript
var ws = new RobustWebSocket('ws://echo.websocket.org/', null {
   // The number of milliseconds to wait before a connection is considered to have timed out. Defaults to 4 seconds.
   timeout: 4000,
  // A function that given a CloseEvent or an online event (https://developer.mozilla.org/en-US/docs/Online_and_offline_events) and the `RobustWebSocket`,
  // will return the number of milliseconds to wait to reconnect, or a non-Number to not reconnect.
  // see below for more examples.
  shouldReconnect: function(event, thisRobustWebsocket) {
    return thisRobustWebsocket.reconnects <= 20 && 0
  },
  // A boolean indicating whether or not to open the connection automatically. Defaults to true, matching native [WebSocket] behavior.
  // You can open the websocket by calling `open()` when you are ready. You can close and re-open the RobustWebSocket instance as much as you wish.
  automaticOpen: true
})
```

**Comment by john-doherty** [comment]
Yeah that's much better. Nice project btw: I spent the evening writing something similar before finding yours, the tests around it were the big selling point.

I'll fork/tweak/pull request the docs as I get to know the object better and have a little more time.

**Comment by nathanboktae** [comment]
> tNice project btw: I spent the evening writing something similar before finding yours, the tests around it were the big selling point.

Thanks :) Yup that was 3-4x the work than just writing the code, given the nature of this problem, but worth it for the peace of mind.
