### ISSUE TITLE
Clarify docs on reconnecting

### ISSUE THREAD

**Issue by halt-hammerzeit** [appuri/robust-websocket#8]
Reconnect only on some whitelisted codes, and only 3 attempts, except on online events, then connect immediately

```js
function shouldReconnect(event, ws) {
  if (event.type === 'online') return 0
  return [1006,1011,1012].indexOf(event.code) && [1000,5000,10000][ws.attempt]
}
```

Why isn't `event.type === 'online'` **always**? Why would it even reconnect on `offline` when there's no point in doing so? Does the default implementation attempt to reconnect in `offline` mode too?

Why wouldn't you reconnect on 1008 (HTTP 400 equivalent) and 1011 (HTTP 500 equivalent) by default: what's the point of that? If 1008 then the data is incorrect and it's a bug in client-side code and the developers should be at least notified about that by the rising amount of errors in their monitoring software. If 1011 then it's "Internal error" and that means that there's a bug in server-side code (maybe "out of memory" even) and that this bug will be fixed and what then? No more reconnection when the error is fixed? That's irrational.

Reconnect immediately but only 20 times per RobustWebSocket instance

```js
function shouldReconnect(event, ws) {
  return ws.reconnects <= 20 && 0
}
```

Why the cryptic `&& 0` in the end? Why not simply return `false`?

**Comment by halt-hammerzeit** [comment]
Also the compatibility table at the top scares off people:

"What do you mean it won't work in iPhone 9.3?
I'm not using it then"

**Comment by halt-hammerzeit** [comment]
Why is it even being so strict when caniuse says that WebSockets are widely-adopted
http://caniuse.com/#search=WebSocket

**Comment by halt-hammerzeit** [comment]
And the link to customevent npm package is broken.
I suggest using this one instead: https://github.com/krambuhl/custom-event-polyfill

**Comment by halt-hammerzeit** [comment]
And what about:

"1000	CLOSE_NORMAL	Normal closure; the connection successfully completed whatever purpose for which it was created."

Should you even be reconnecting by default on that status code?
I guess not.

**Comment by nathanboktae** [comment]
> Why isn't event.type === 'online' always?

Because it can be a `CloseEvent` or an offline / online event.

> Why would it even reconnect on offline when there's no point in doing so? Does the default implementation attempt to reconnect in offline mode too?

If the browser is offline, (`shouldReconnect` will not be called)[https://github.com/appuri/robust-websocket/blob/master/robust-websocket.js#L110-L113]

> Why wouldn't you reconnect on 1008 (HTTP 400 equivalent) and 1011 (HTTP 500 equivalent) by default: what's the point of that?

400 means the request you formed is bad. If you try the exact same request again, you should always get 400. 400 is not a transient error. If it is, the API is using the wrong status code. 1011 is retried, double-check the code again.

> If 1008 then the data is incorrect and it's a bug in client-side code

No it could be the end user's fault. A username is already taken, or other server-side only validation logic is triggered. Either way retrying does not help.

> That's irrational.

You can always provide your own function here.

> Why the cryptic `&& 0` in the end?

that can be rewritten as

```javascript
function shouldReconnect(event, ws) {
  if (ws.reconnects <= 20) {
    return 0
  } else {
    return false
  }
}
```

> What do you mean it won't work in iPhone 9.3?

It does; tests are just not as stable as I'd like them to be.

> I suggest using this one instead: https://github.com/krambuhl/custom-event-polyfill

Thanks. I'll take a look

**Comment by halt-hammerzeit** [comment]
Oh, thx mate, that's a thorough explanation.

Ok, `shouldReconnect` is a difficult one to grasp.

> 1011 is retried, double-check the code again.

```js
```

**Comment by halt-hammerzeit** [comment]
> 1011 is retried, double-check the code again.

```js
  RobustWebSocket.defaultOptions = {
    // the time to wait before a successful connection
    // before the attempt is considered to have timed out
    timeout: 4000,
    // Given a CloseEvent or OnlineEvent and the RobustWebSocket state,
    // should a reconnect be attempted? Return the number of milliseconds to wait
    // to reconnect (or null or undefined to not), rather than true or false
    shouldReconnect: function(event, ws) {
      if (event.code === 1008 || event.code === 1011) return
      return [0, 3000, 10000][ws.attempts]
    },
```

The code tells that it's not retried: if the connection was closed due to a `1011` error then it's gone, forever.
Same for `1008`: if a client sends a single wrong request and gets `1008` then the connection is gone, forever.

**Comment by nathanboktae** [comment]
sorry I thought you were only talking about the example code in the above box.

No 1011 (500) is not retried by the default `shouldReconnect`. a 500 will usually either be a big in the server that the code is hitting, and retrying won't help, or the server is down and getting slammed, and retrying will just slam it more. Sure the server will probably eventually come back up so retrying it at a longer interval would be fine.

> Same for 1008: if a client sends a single wrong request 

Remember we're talking about WebSockets - a persistent two-way communication channel, not request-response-and-done HTTP. So 1008 could be from the initial connection attempt, or maybe one message is bad - but would your server connection kill it over 1 bad message? maybe? A lot depends on your application.

**Comment by halt-hammerzeit** [comment]
Ok, thanks for the explanations, that was really helpful 👍

**Comment by nathanboktae** [comment]
np glad to help. I'd higher recommend providing your own `shouldReconnect` function that fits your app usage. Thanks!
