### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by halt-hammerzeit** [appuri/robust-websocket#9]
When rendering on the server side.
It's because of the way you defined your module: you assume it's only `require()`d on the client side.

**Comment by nathanboktae** [comment]
> When rendering on the server side.

This project is only for the browser. It's specifically a wrapper around the W3C standard `WebSocket` class. If you want a node.js package for a client websocket, [check out `ws`](https://www.npmjs.com/package/ws)

**Comment by halt-hammerzeit** [comment]
Ok, then for those coming from Google: the workaround is `global.navigator = {}`

**Comment by nathanboktae** [comment]
Are you trying to use webpack or browserify with this?

**Comment by halt-hammerzeit** [comment]
No, I'm just running my server-side code which happens to `require()` your package and this seems to trigger that `function (something, navigator)` is evaluated.
I.e. I'm not even using your library on the server, it just happens to be `require()`d among the others (this is a React rendering librar)
